### ISSUE TITLE
N-N relationship between leaf node and field?

### ISSUE THREAD

**Issue by pH142857** [doug-101/TreeTag#6]
Taking the Movies_sample example file, could a movie have several genres, or several services? Could we have a movie that is broadcasted at the same time by Netflix and by HBO, or which is at the same time Drama and Science-Fiction?

So, more formally: database-wise, could a leaf node bear several occurrences of a field (aka a N-N relationship)? Or, programming-wise, could a field be a table of elements?

This seems a rather obvious use case to me, am I missing something on how to achieve that?

**Comment by duarteframos** [comment]
No it doesn't seem to support that, but the sibling Treeline does, I think https://treeline.bellz.org/

**Comment by doug-101** [comment]
You are correct, TreeTag doesn't support multiple entries in the same field.

I've also run into use cases where that would be handy.  I've hesitated to add it because it's a big change to support it globally.

But this request made me reconsider, so I'll start looking into adding it.  I'll let you know how it goes...

**Comment by doug-101** [comment]
I finally got this added.  It took more work than I originally expected.  Multiple entries can now be made for a field.

It is included in newly-released version 0.8.0.  See the last paragraph of the Configure Fields section of the ReadMe/Help files for details about usage.

**Comment by pH142857** [comment]
Thanks!
